{% set name = "lintrunner" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lintrunner-{{ version }}.tar.gz
  sha256: b9a76e54d51852ccb452362b53d2f960f8f3a1a69bba5bfe156032e47430fbbe

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0
  # This is a package on PyPI, that builds only an executable
  # and no python extension
  ignore_run_exports_from:
    - python *
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python 3.12.*                       # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python 3.12.*
    - maturin >=0.12,<0.13
    - pip

test:
  commands:
    - lintrunner --version

about:
  home: https://pypi.org/project/lintrunner/
  summary: A lint running tool and framework.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
