{% set name = "lintrunner" %}
{% set version = "0.12.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lintrunner-{{ version }}.tar.gz
  sha256: de030dfc6de23b561f98be731d12b505a40290450ba8d15e6a611a18c3ad95a8

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0
  # This is a package on PyPI, that builds only an executable
  # and no python extension
  ignore_run_exports_from:
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python >=3.6
    - maturin >=0.12,<0.13
    - pip

test:
  commands:
    - lintrunner --version

about:
  home: https://pypi.org/project/lintrunner/
  summary: A lint running tool and framework.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
