{% set name = "lintrunner" %}
{% set version = "0.12.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lintrunner-{{ version }}.tar.gz
  sha256: e4c8fdb0b28ed24758543d20ece9918f7c8094b311e86ad9e882841fed7a36c9

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0
  skip: true  # [not is_python_min]
  # This is a package on PyPI, that builds only an executable
  # and no python extension
  ignore_run_exports_from:
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python {{ python_min }}.*           # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python {{ python_min }}.*
    - maturin >=0.12,<0.13
    - pip

test:
  commands:
    - lintrunner --version

about:
  home: https://pypi.org/project/lintrunner/
  summary: A lint running tool and framework.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
