{% set name = "lintrunner" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lintrunner-{{ version }}.tar.gz
  sha256: 21dbdfb4d5f59fe2554598d091cae78b81737e5ae27d7d12ac59d9a09bd0fe97

build:
  script:
    - {{ PYTHON }} -m pip install . -vv
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 1
  # This is a package on PyPI, that builds only an executable
  # and no python extension
  ignore_run_exports_from:
    - python
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cargo-bundle-licenses
  host:
    - python >=3.6
    - maturin >=0.12,<0.13
    - pip

test:
  commands:
    - lintrunner --version

about:
  home: https://pypi.org/project/lintrunner/
  summary: A lint running tool and framework.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - isuruf
